import { Report, Province } from "./types";

export const mockReports: Report[] = [
  {
    id: "1",
    category: "Deforestation",
    description:
      "Large-scale deforestation observed near the community forest. Several trees have been cut down illegally.",
    photos: [
      "https://images.pexels.com/photos/1268076/pexels-photo-1268076.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    province: "Bagmati",
    district: "Kathmandu",
    address: "Shivapuri National Park Area",
    location: { lat: 27.7833, lng: 85.3833 },
    date: "2025-12-28",
    reporter: { name: "Rajesh Shrestha", email: "rajesh@example.com" },
  },
  {
    id: "2",
    category: "River Pollution",
    description:
      "Industrial waste being dumped directly into Bagmati River. Strong chemical odor detected.",
    photos: [
      "https://images.pexels.com/photos/2768961/pexels-photo-2768961.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    province: "Bagmati",
    district: "Lalitpur",
    address: "Bagmati River, Balkhu Bridge",
    location: { lat: 27.6833, lng: 85.2833 },
    date: "2025-12-29",
    reporter: { name: "Sita Rai", email: "sita@example.com" },
  },
  {
    id: "3",
    category: "Waste Dumping",
    description:
      "Illegal dumping site near residential area. Plastic and medical waste visible.",
    photos: [
      "https://images.pexels.com/photos/2768961/pexels-photo-2768961.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/3584069/pexels-photo-3584069.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    province: "Gandaki",
    district: "Pokhara",
    address: "Near Fewa Lake Shore",
    location: { lat: 28.2096, lng: 83.9856 },
    date: "2025-12-30",
    reporter: { name: "Anil Gurung", email: "anil@example.com" },
  },
  {
    id: "4",
    category: "Forest Fires",
    description:
      "Forest fire spreading rapidly in the hillside. Immediate action required.",
    photos: [
      "https://images.pexels.com/photos/266487/pexels-photo-266487.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    province: "Karnali",
    district: "Surkhet",
    address: "Bardiya Forest Area",
    location: { lat: 28.6, lng: 81.6167 },
    date: "2025-12-31",
    reporter: { name: "Maya Thapa", email: "maya@example.com" },
  },
  {
    id: "5",
    category: "Landslides",
    description:
      "Major landslide blocking highway. Risk to nearby settlements.",
    photos: [
      "https://images.pexels.com/photos/4571013/pexels-photo-4571013.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    province: "Koshi",
    district: "Dhankuta",
    address: "Dharan-Dhankuta Highway",
    location: { lat: 26.9833, lng: 87.3333 },
    date: "2025-12-27",
    reporter: { name: "Krishna Limbu", email: "krishna@example.com" },
  },
  {
    id: "6",
    category: "Wildlife Threats",
    description: "Poachers spotted near endangered red panda habitat.",
    photos: [
      "https://images.pexels.com/photos/2295744/pexels-photo-2295744.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    province: "Sudurpashchim",
    district: "Darchula",
    address: "Api Nampa Conservation Area",
    location: { lat: 29.8167, lng: 80.5667 },
    date: "2025-12-26",
    reporter: { name: "Binod Bista", email: "binod@example.com" },
  },
];

export const districtsByProvince: Record<Province, string[]> = {
  Koshi: [
    "Bhojpur",
    "Dhankuta",
    "Ilam",
    "Jhapa",
    "Khotang",
    "Morang",
    "Okhaldhunga",
    "Panchthar",
    "Sankhuwasabha",
    "Solukhumbu",
    "Sunsari",
    "Taplejung",
    "Terhathum",
    "Udayapur",
  ],
  Madhesh: [
    "Bara",
    "Dhanusha",
    "Mahottari",
    "Parsa",
    "Rautahat",
    "Saptari",
    "Sarlahi",
    "Siraha",
  ],
  Bagmati: [
    "Bhaktapur",
    "Chitwan",
    "Dhading",
    "Dolakha",
    "Kathmandu",
    "Kavrepalanchok",
    "Lalitpur",
    "Makwanpur",
    "Nuwakot",
    "Ramechhap",
    "Rasuwa",
    "Sindhuli",
    "Sindhupalchok",
  ],
  Gandaki: [
    "Baglung",
    "Gorkha",
    "Kaski",
    "Lamjung",
    "Manang",
    "Mustang",
    "Myagdi",
    "Nawalpur",
    "Parbat",
    "Syangja",
    "Tanahun",
  ],
  Lumbini: [
    "Arghakhanchi",
    "Banke",
    "Bardiya",
    "Dang",
    "Gulmi",
    "Kapilvastu",
    "Palpa",
    "Parasi",
    "Pyuthan",
    "Rolpa",
    "Rukum East",
    "Rupandehi",
  ],
  Karnali: [
    "Dailekh",
    "Dolpa",
    "Humla",
    "Jajarkot",
    "Jumla",
    "Kalikot",
    "Mugu",
    "Rukum West",
    "Salyan",
    "Surkhet",
  ],
  Sudurpashchim: [
    "Achham",
    "Baitadi",
    "Bajhang",
    "Bajura",
    "Dadeldhura",
    "Darchula",
    "Doti",
    "Kailali",
    "Kanchanpur",
  ],
};

export const ISSUE_CATEGORIES = [
  "Deforestation",
  "Landslides",
  "River Pollution",
  "Waste Dumping",
  "Forest Fires",
  "Wildlife Threats",
  "Other",
];

export const Provinces = [
  "Koshi",
  "Madhesh",
  "Bagmati",
  "Gandaki",
  "Lumbini",
  "Karnali",
  "Sudurpashchim",
];
